Models/News.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace SparklingHome.Models
{
    public class News
    {
        public string Id { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string PostedBy { get; set; }
        public string DatePosted { get; set; }
        public string Image { get; set; }
    }
}

Controllers/NewsController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SparklingHome.Models;
using System.Net.Http;
using Newtonsoft.Json;

namespace SparklingHome.Controllers
{
    public class NewsController : Controller
    {
        // retrieve news articles from api gateway endpoint
        private const string sparklinghomeNewsEndpoint = "https://15xpego1h2.execute-api.us-east-1.amazonaws.com/sparklinghome/news";

        private async Task<List<News>> GetNewsArticles(string resource)
        {
            HttpClient client = new HttpClient();
            try
            {
                HttpResponseMessage response = await client.GetAsync(resource);

                if (response.IsSuccessStatusCode)
                {
                    string news = await response.Content.ReadAsStringAsync();
                    List<News> newsDeserialised = JsonConvert.DeserializeObject<List<News>>(news);

                    return newsDeserialised;
                }
                else
                {
                    return new List<News>();
                }
            }
            catch (Exception exception)
            {
                return new List<News>();
            }
        }

        public async Task<IActionResult> Index(string? SortOption)
        {
            Tuple<List<News>, bool> newsSortTuple;
            if (SortOption != null)
            {
                newsSortTuple = SortOption == "latest"
                    ? Tuple.Create(await GetNewsArticles(sparklinghomeNewsEndpoint + "?sort=latest"), true)
                    : Tuple.Create(await GetNewsArticles(sparklinghomeNewsEndpoint), false);
            }
            else
            {
                newsSortTuple = Tuple.Create(await GetNewsArticles(sparklinghomeNewsEndpoint), true);
            }

            return View(newsSortTuple);
        }

        public async Task<IActionResult> NewsArticle(string newsId)
        {
            List<News> newsArticle = await GetNewsArticles(sparklinghomeNewsEndpoint + "/" + newsId);
            return View(newsArticle.First());
        }

    }
}

Views/News/Index.cshtml
@model Tuple<List<News>, bool>

<form class="d-flex justify-content-end flex-row align-items-center"
      asp-action="Index"
      asp-controller="News" method="post">
    <div class="text-muted mr-2">Sort articles by: </div>
    <select class="custom-select w-25" name="SortOption" onchange="this.form.submit()">
        <option value="default">Default</option>
        <option value="latest" selected="@Model.Item2">Latest</option>
    </select>
</form>

<section class="container d-flex justify-content-start flex-column mt-5">
    @foreach (var news in Model.Item1)
    {
        <div class="card mb-3 w-75 mt-2">
            <div class="row no-gutters">
                <div class="col-md-4">
                    <img src="@news.Image/500/500" class="img-fluid" alt="...">
                </div>
                <div class="col-md-8">
                    <div class="card-body">
                        <h5 class="card-title">@news.Title</h5>
                        <pre class="card-text text-break overflow-hidden"
                             style="text-overflow: ellipsis;
                                  display: -webkit-box;
                                  -webkit-line-clamp: 5;
                                  -webkit-box-orient: vertical;
                                  white-space: normal;
                                  font-family: inherit">
                            @news.Content
                        </pre>
                        <div class="d-flex flex-row justify-content-between">
                            <p class="card-text"><small class="text-muted">@news.DatePosted</small></p>
                            <a class="card-link" 
                               asp-controller="News" 
                               asp-action="NewsArticle" 
                               asp-route-newsId="@news.Id">
                                View More
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    }
</section>

<script src="~/js/news.js"></script>

Views/News/NewsArticle.cshtml
@model News

<h2 class="mt-2">@Model.Title</h2>
<div class="d-flex justify-content-start mt-4">
    <div class="text-muted">Posted by: @Model.PostedBy</div>
    <div class="text-muted ml-5">Date posted: @Model.DatePosted</div>
</div>

<img class="img-fluid mt-4" src="@Model.Image/1100/500" />

<article class="container mt-2 mb-3" style="white-space: break-spaces; font-family: inherit">
    @Model.Content
</article>